# Generated by Django 4.2 on 2023-04-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings_diary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=80)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
